updated deploy.sh file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -85,15 +85,20 @@ jobs:
 
           echo "List after deleting...."
           ls -al
-          
+
           # Check if the out folder exists and has files
-          if [ -d "out" ] && [ "$(ls -A out)" ]; then
-              echo "Copying files from the 'out' folder..."
-              cp -a out/. .  # Copies everything from 'out' to the root directory
-          else
-              echo "'out' directory is missing or empty. Skipping deployment."
-              exit 1  # Exit the script if 'out' folder is not found or is empty
-          fi
+          # if [ -d "out" ] && [ "$(ls -A out)" ]; then
+          #     echo "Copying files from the 'out' folder..."
+          #     cp -a out/. .  # Copies everything from 'out' to the root directory
+          # else
+          #     echo "'out' directory is missing or empty. Skipping deployment."
+          #     exit 1  # Exit the script if 'out' folder is not found or is empty
+          # fi
+
+          cp out/* .
+
+          echo "List after copying from out to root...."
+          la -al
 
           # Stage all changes
           git add .
